"""Subject roster: slug -> English Wikipedia article title."""

CELEBS: dict[str, str] = {
    "stanley-tucci": "Stanley Tucci",
    "peter-garrett": "Peter Garrett",
    "john-malkovich": "John Malkovich",
    "ben-kingsley": "Ben Kingsley",
    "jk-simmons": "J. K. Simmons",
    "paul-giamatti": "Paul Giamatti",
    "paul-kelly": "Paul Kelly (Australian musician)",
    "dean-norris": "Dean Norris",
    "keegan-michael-key": "Keegan-Michael Key",
    "the-rock": "Dwayne Johnson",
    "jason-alexander": "Jason Alexander",
    "patrick-stewart": "Patrick Stewart",
    "samuel-l-jackson": "Samuel L. Jackson",
    "danny-devito": "Danny DeVito",
    "jason-statham": "Jason Statham",
    "phil-collins": "Phil Collins",
    "sean-connery": "Sean Connery",
    "bruce-willis": "Bruce Willis",
    "woody-harrelson": "Woody Harrelson",
    "terry-crews": "Terry Crews",
    "vin-diesel": "Vin Diesel",
    "pitbull": "Pitbull (rapper)",
    "john-travolta": "John Travolta",
    "billy-zane": "Billy Zane",
}
